name: products_1
description: "product information"
sources:
  - integration_name: Sales-Eng-PoC
    s3:
      access_key: ""
      secret_access: ""
      prefix: null
      pattern: rockset/retail/olist_products_dataset.csv
      region: us-west-2
      bucket: customer-poc-data
    format_params:
      json: false
      csv:
        encoding: UTF-8
        firstLineAsColumnNames: true
        separator: ","
        columnNames:
          - "product_id"
          - "category_br"
          - "name_len"
          - "desc_len"
          - "photo_cnt"
          - "weight_g"
          - "length_cm"
          - "height_cm"
          - "width_cm"
        columnTypes:
          - string
          - string
          - int
          - int
          - int
          - int
          - int
          - int
          - int
field_mappings:
  - name: primaryKey
    input_fields:
      - field_name: product_id
        if_missing: SKIP
        is_drop: false
        param: id_str
    output_field:
      field_name: _id
      value: 
        sql: ":id_str"
      on_error: FAIL
  - name: dropNameLen
    input_fields:
      - field_name: name_len
        if_missing: SKIP
        is_drop: true
  - name: dropDescLen
    input_fields:
      - field_name: desc_len
        if_missing: SKIP
        is_drop: true
  - name: dropPhotoCnt
    input_fields:
      - field_name: photo_cnt
        if_missing: SKIP
        is_drop: true